sudo: false

branches:
  only:
    - gh-pages
    - /.*/

script:
  - echo 'Deploying to GH pages...'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: gh-pages
