sudo: false
language: python
python: 
  - "3.6"

branches:
  only:
    - gh-pages
    - /.*/

script:
  - python generate.py

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: gh-pages
