sudo: false
language: python
python: 
  - "3.6"

install:
  - python -m pip install -r requirements.txt

script:
  - python generate.py

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
