sudo: false
language: python
python: 
  - "3.6"

install:
  - python -m pip install -r requirements.txt

before_script:
  - python -m flake8 generate.py

script:
  - python generate.py

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
