sudo: false
language: python
python: 
  - "3.6"

install:
  - make init

before_script:
  - make lint

script:
  - make generate

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
