name: Deploy to Pages

on:
  push:
    branches: [master, main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - run: pip install -r requirements.txt

      - name: Build
        run: python generate.py

      - name: Push to gh-pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "no-reply@github.com"

          git add index.md
          git commit -m 'Deploy to gh-pages'
          git checkout -b gh-pages
          if git fetch origin gh-pages; then
            git merge origin/gh-pages
          fi
          git push origin gh-pages:gh-pages
